apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-pv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-pv
  template:
    metadata:
      labels:
        app: flask-pv
    spec:
      containers:
        - name: flask-container
          image: parilvadher/flaskapp:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: ClusterIP
  selector:
    app: flask-pv
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
